config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,controllers: {
    sessions: "public/sessions",
    passwords: "public/passwords",
    registrations: "public/registrations"
  }
  devise_for :admin,controllers: {
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    registrations: "admin/registrations"
  }

  # 会員側のルーティング設定
  root to: "public/homes#top"
  get "about" => "public/homes#about", as: "about"
  get "customers/my_page" => "public/customers#show", as: "customer"
  get "customers/information/edit" => "public/customers#edit", as: "edit_customer"
  patch "customers/information" => "public/customers#update"
  get "customers/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe_customer"
  patch "customers/withdraw" => "public/customers#withdraw"
  scope module: :public do
    resources :items, only:[:index, :show, :update]
    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :addresses, only:[:index, :edit, :create, :update ,:destroy]
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
         post "confirm"
         get "complete"
      end
    end
  end


  # 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  enum is_deleted: { #会員ステータス
    有効: false,
    退会: true
  }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_one_attached :item_image

  enum is_active: { #販売ステータス
    販売中: true,
    販売停止中: false
  }

  def with_tax_price #税込の表示
    (price * 1.1).floor
  end


  def get_item_image(width,height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpeg')
      item_image.attach(io: File.open(file_path), filename: 'noimage.jpeg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

enum payment_method: { #支払方法
  credit_card: 0,
  transfer: 1
}

enum status: { #注文ステータス
  waiting_for_payment: 0,
  payment_confirmation: 1,
  production: 2,
  preparing_to_ship: 3,
  shipped: 4
}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true

  enum making_status: { #製作ステータス
  can_not_production: 0,
  waiting_for_production: 1,
  production: 2,
  completion_of_production: 3
}

def subtotal
  item.with_tax_price * amount
end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to  admin_customer_path
  end

   private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to  admin_items_path
  end


 private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :item_image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!, except: [:index, :show, :top, :about, :edit, :update, :new, :create]
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/customers/edit.html.erb
<div class='container'>
  <h3><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h3>

  <div class='row'>
    <div class="col">
      <%= form_with model: @customer, url: admin_customer_path do |f| %>
        <div class="form-group">
          <%= f.label :id, "会員ID", class: "col-sm-4 col-form-label" %>
          <%= @customer.id %>
        </div>

        <div class="form-group">
          <%= f.label "氏名", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :last_name %>　　　<%= f.text_field :first_name %>
        </div>

        <div class="form-group">
          <%= f.label "フリガナ", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :last_name_kana %>　　　<%= f.text_field :first_name_kana %>
        </div>

        <div class="form-group">
          <%= f.label :postal_code, "郵便番号", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :postal_code %>
        </div>

        <div class="form-group">
          <%= f.label "住所", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :address, size: 60 %>
        </div>

        <div class="form-group">
          <%= f.label "電話番号", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :telephone_number %>
        </div>

        <div class="form-group">
          <%= f.label :email, "メールアドレス", class: "col-sm-4 col-form-label" %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>

        <div class="form-group">
          <%= f.label :is_deleted, "会員ステータス", class: "col-sm-4 col-form-label" %>
          <%= f.radio_button :is_deleted, :"有効", checked: true %>
          <%= f.label :is_deleted, "有効", value: false, class: "col-sm-3 col-form-label" %>
          <%= f.radio_button :is_deleted, :"退会" %>
          <%= f.label :is_deleted, "退会", value: true, class: "col-sm-3 col-form-label" %>
        </div>

        <%= f.submit '変更を保存', class:"btn btn-success" %>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container'>
  <h3>会員一覧</h3>

  <table class='table'>
    <thead>
      <tr class="table-secondary">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.last_name+customer.first_name, admin_customer_path(customer.id), class: "text-dark", style: "padding: 1px; border-bottom: solid 1px black;"%></td>
          <td><%= customer.email %></td>
          <td><%= customer.is_deleted %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
  <h3><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h3>

  <div class='row'>
    <div class="col">
      <%= form_with model: @customer, url: admin_customer_path do |f| %>
        <div class="form-group">
          <%= f.label :id, "会員ID", class: "col-sm-4 col-form-label" %>
          <%= @customer.id %>
        </div>

        <div class="form-group">
          <%= f.label :name, "氏名", class: "col-sm-4 col-form-label" %>
          <%= @customer.last_name %>　<%= @customer.first_name %>
        </div>

        <div class="form-group">
          <%= f.label :last_name_kana, "フリガナ", class: "col-sm-4 col-form-label" %>
          <%= @customer.last_name_kana %>　<%= @customer.first_name_kana %>
        </div>

        <div class="form-group">
          <%= f.label :postal_code, "郵便番号", class: "col-sm-4 col-form-label" %>
          <%= @customer.postal_code %>
        </div>

        <div class="form-group">
          <%= f.label "住所", class: "col-sm-4 col-form-label" %>
          <%= @customer.address %>
        </div>

        <div class="form-group">
          <%= f.label "電話番号", class: "col-sm-4 col-form-label" %>
          <%= @customer.telephone_number %>
        </div>

        <div class="form-group">
          <%= f.label :email, "メールアドレス", class: "col-sm-4 col-form-label" %>
          <%= @customer.email %>
        </div>

        <div class="form-group">
          <%= f.label :is_deleted, "会員ステータス", class: "col-sm-4 col-form-label" %>
          <%= @customer.is_deleted %>
        </div>

        <div class="d-flex justify-content-around">
          <%= link_to "編集する",  edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
          <%= link_to "注文履歴一覧を見る", admin_order_path, class: "btn btn-primary" %>
        </div>


      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>