config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,controllers: {
    sessions: "public/sessions",
    passwords: "public/passwords",
    registrations: "public/registrations"
  }
  devise_for :admin,controllers: {
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    registrations: "admin/registrations"
  }

  # 会員側のルーティング設定
  root to: "public/homes#top"
  get "about" => "public/homes#about", as: "about"
  get "customers/my_page" => "public/customers#show", as: "customer"
  get "customers/information/edit" => "public/customers#edit", as: "edit_customer"
  patch "customers/information" => "public/customers#update"
  get "customers/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe_customer"
  patch "customers/withdraw" => "public/customers#withdraw"
  scope module: :public do
    resources :items, only:[:index, :show, :update]
    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :addresses, only:[:index, :edit, :create, :update ,:destroy]
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
         post "confirm"
         get "complete"
      end
    end
  end


  # 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  enum is_deleted: { #会員ステータス
    有効: false,
    退会: true
  }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_one_attached :item_image

  enum is_active: { #販売ステータス
    販売中: true,
    販売停止中: false
  }

  def with_tax_price #税込の表示
    (price * 1.1).floor
  end


  def get_item_image(width,height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpeg')
      item_image.attach(io: File.open(file_path), filename: 'noimage.jpeg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

enum payment_method: { #支払方法
  credit_card: 0,
  transfer: 1
}

enum status: { #注文ステータス
  waiting_for_payment: 0,
  payment_confirmation: 1,
  production: 2,
  preparing_to_ship: 3,
  shipped: 4
}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true

  enum making_status: { #製作ステータス
  can_not_production: 0,
  waiting_for_production: 1,
  production: 2,
  completion_of_production: 3
}

def subtotal
  item.with_tax_price * amount
end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to  admin_items_path
  end


 private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :item_image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    # @order_details = OrderDetail.where(order_id: params[:id])
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @postage = 800
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to  admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :postage, :payment_method, :total_payment, :status, :created_at)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!, except: [:index, :show, :top, :about, :edit, :update, :new, :create]
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/orders/show.html.erb
<div class='container'>
  <h3>注文履歴詳細</h3>

  <div class='row'>
    <div class="col">
      <table class="table table-borderless">
        <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
          <tr>
            <th>購入者</th>
            <td><%= @order.name %></td>
          </tr>
          <tr>
             <th>注文日</th>
             <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
           <tr>
            <th>配送先</th>
            <td>〒<%= @order.postal_code %>
              <%= @order.address %><br>
              <%= @order.name %>
            </td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method_i18n%></td>
          </tr>
            <th>注文ステータス</th>
            <td>
              <%= f.select :status, Order.statuses_i18n.invert %>
              <%= f.submit "更新" , class: "btn btn-success" %>
            </td>
          </tr>
        <% end %>
      </table>
      
      <div class="container">
        <div class="row">
          <div class="col-8">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>商品名</th>
                  <th>単価(税込)</th>
                  <th>数量</th>
                  <th>小計</th>
                  <th>製作ステータス</th>
                </tr>
              </thead>
              <tbody>
                <% @total = 0 %>
                <% @order_details.each do |order_detail| %>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id) do |f| %>
                <% @total += order_detail.subtotal %>
                <tr>
                  <td><%= order_detail.item.name %></td>
                  <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
                  <td><%= order_detail.amount %></td>
                  <td><%= order_detail.subtotal.to_s(:delimited) %></td>
                  <td>
                    <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                    <%= f.submit "更新" , class: "btn btn-success" %>
                  </td>
                </tr>
                <% end %>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="col-4">
            <table class="table table-borderless">
              <tr>
                <th>商品合計</th>
                <td><%= (@order.total_payment - @postage).to_s(:delimited) %>円</td>
              </tr>
              <tr>
                <th>送料</th>
                <td><%= @postage %>円</td>
              </tr>
              <tr>
                <th>請求金額合計</th>
                <td><%= @order.total_payment.to_s(:delimited) %>円</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>