config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,controllers: {
    sessions: "public/sessions",
    passwords: "public/passwords",
    registrations: "public/registrations"
  }
  devise_for :admin,controllers: {
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    registrations: "admin/registrations"
  }

  # 会員側のルーティング設定
  root to: "public/homes#top"
  get "about" => "public/homes#about", as: "about"
  get "customers/my_page" => "public/customers#show", as: "customer"
  get "customers/information/edit" => "public/customers#edit", as: "edit_customer"
  patch "customers/information" => "public/customers#update"
  get "customers/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe_customer"
  patch "customers/withdraw" => "public/customers#withdraw"
  scope module: :public do
    resources :items, only:[:index, :show, :update]
    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :addresses, only:[:index, :edit, :create, :update ,:destroy]
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
         post "confirm"
         get "complete"
      end
    end
  end


  # 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  enum is_deleted: { #会員ステータス
    有効: false,
    退会: true
  }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_one_attached :item_image

  enum is_active: { #販売ステータス
    販売中: true,
    販売停止中: false
  }

  def with_tax_price #税込の表示
    (price * 1.1).floor
  end


  def get_item_image(width,height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpeg')
      item_image.attach(io: File.open(file_path), filename: 'noimage.jpeg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

enum payment_method: { #支払方法
  credit_card: 0,
  transfer: 1
}

enum status: { #注文ステータス
  waiting_for_payment: 0,
  payment_confirmation: 1,
  production: 2,
  preparing_to_ship: 3,
  shipped: 4
}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true

  enum making_status: { #製作ステータス
  can_not_production: 0,
  waiting_for_production: 1,
  production: 2,
  completion_of_production: 3
}

def subtotal
  item.with_tax_price * amount
end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to  admin_items_path
  end


 private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :item_image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!, except: [:index, :show, :top, :about, :edit, :update, :new, :create]
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<div class='container'>
  <h3>ジャンル編集</h3>
  <div class='row'>
    <div class="col-sm-30 col-lg-5 px-sm-0 mx-auto">
      <%= form_with model: @genre, url: admin_genre_path do |f| %>
        <div class="form-group row mb-3">
          <%= f.label :name, "ジャンル名", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :name, id:"genre_name" %>
          <%= f.submit '変更を保存', class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class='container'>
  <h3>ジャンル一覧・追加</h3>
  <div class='row'>
    <div class="col-sm-30 col-lg-5 px-sm-0 mx-auto">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <div class="form-group row mb-3">
          <%= f.label :name, "ジャンル名", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :name, placeholder: "ジャンル名" %>
          <%= f.submit '新規登録', class:"btn btn-success" %>
        </div>
      <% end %>
    </div>

    <table class="table table-hover table-inverse">
      <thead>
        <tr class="table-active">
          <th>ジャンル</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/edit.html.erb
<div class='container'>
  <h3>商品編集</h3>

  <div class='row'>
    <div class="col-sm-30 col-lg-5 px-sm-0 mx-auto">

      <%= form_with model: @item, url: admin_item_path do |f| %>

        <div class="form-group row mb-3">
          <%= f.label :name, "商品画像", class: "col-sm-4 col-form-label" %>
          <%= f.file_field :item_image,  accept: "image/*" %>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :name, "商品名", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :name, placeholder: "商品名", size: 35 %>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :name, "商品説明", class: "col-sm-4 col-form-label" %>
          <%= f.text_area :introduction, rows: 8, cols: 34 %>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :genre_id, "ジャンル", class: "col-sm-4 col-form-label" %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, options = { include_blank: "--選択してください--"}, :style => "width:310px" %>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :name, "税抜価格", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :price, placeholder: 1000, size: 35 %>円
        </div>

        <div class="form-group row mb-3">
          <%= f.label :is_active, "販売ステータス", class: "col-sm-4 col-form-label" %>
          <%= f.radio_button :is_active, :"販売中", checked: true %>
          <%= f.label :is_active, "販売中", value: true, class: "col-sm-3 col-form-label" %>
          <%= f.radio_button :is_active, :"販売停止中" %>
          <%= f.label :is_active, "販売停止中", value: false, class: "col-sm-3 col-form-label" %>
        </div>

        <div class="form-group text-center">
          <%= f.submit '変更を保存', class:"btn btn-success" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container'>
  <h3>商品一覧</h3>
  <div class="d-flex justify-content-end container" style="margin-top:-40px">
    <%= link_to new_admin_item_path do %>
      <i class="fa fa-plus-circle fa-2x" style="color: black;"></i>
    <% end %>
  </div>

  <table class='table'>
    <thead>
       <tr class="table-secondary">
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id), class: "text-dark", style: "padding: 1px; border-bottom: solid 1px black;" %></td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
          <td><%= item.is_active %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center container"><%= paginate @items %></div>
</div>

app/views/admin/items/new.html.erb
<div class='container'>
  <h3>商品新規登録</h3>

  <div class='row'>
    <div class="col-sm-30 col-lg-5 px-sm-0 mx-auto">

      <%= form_with model: @item, url: admin_items_path do |f| %>

        <div class="form-group row mb-3">
          <%= f.label :name, "商品画像", class: "col-sm-4 col-form-label" %>
          <%= f.file_field :item_image,  accept: "image/*" %>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :name, "商品名", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :name, placeholder: "商品名", size: 35 %>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :name, "商品説明", class: "col-sm-4 col-form-label" %>
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", rows: 8, cols: 34 %>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :genre_id, "ジャンル", class: "col-sm-4 col-form-label" %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, options = { include_blank: "--選択してください--"}, :style => "width:310px" %>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :name, "税抜価格", class: "col-sm-4 col-form-label" %>
          <%= f.text_field :price, placeholder: 1000, size: 35 %>円
        </div>

        <div class="form-group row mb-3">
          <%= f.label :is_active, "販売ステータス", class: "col-sm-4 col-form-label" %>
          <%= f.radio_button :is_active, :"販売中", checked: true %>
          <%= f.label :is_active, "販売中", value: true, class: "col-sm-3 col-form-label" %>
          <%= f.radio_button :is_active, :"販売停止中" %>
          <%= f.label :is_active, "販売停止中", value: false, class: "col-sm-3 col-form-label" %>
        </div>

        <div class="form-group text-center">
          <%= f.submit '新規登録', class:"btn btn-success" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container'>
  <h3>商品詳細</h3>
  <div class='row'>
    <div class="col-4 mx-auto">
      <%= image_tag @item.get_item_image(300,300) %>
    </div>
    <div class="col-8 mx-auto">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>商品名</th>
            <td><%= @item.name %></td>
          </tr>

          <tr>
            <th>商品説明</th>
            <td><%= @item.introduction %></td>
          </tr>

          <tr>
            <th>ジャンル</th>
            <td><%= @item.genre.name %></td>
          </tr>

          <tr>
            <th>税込価格<br>(税抜価格)</th>
            <td><%= @item.with_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)円</td>
          </tr>

          <tr>
            <th>販売ステータス</th>
            <td><%= @item.is_active %></td>
          </tr>
        </thead>
      </table>

      <div class="text-center">
        <%= link_to '編集する',  edit_admin_item_path(@item.id), class: "btn btn-success" %>
      </div>

    </div>
  </div>
</div>