config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,controllers: {
    sessions: "public/sessions",
    passwords: "public/passwords",
    registrations: "public/registrations"
  }
  devise_for :admin,controllers: {
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    registrations: "admin/registrations"
  }

  # 会員側のルーティング設定
  root to: "public/homes#top"
  get "about" => "public/homes#about", as: "about"
  get "customers/my_page" => "public/customers#show", as: "customer"
  get "customers/information/edit" => "public/customers#edit", as: "edit_customer"
  patch "customers/information" => "public/customers#update"
  get "customers/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe_customer"
  patch "customers/withdraw" => "public/customers#withdraw"
  scope module: :public do
    resources :items, only:[:index, :show, :update]
    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :addresses, only:[:index, :edit, :create, :update ,:destroy]
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
         post "confirm"
         get "complete"
      end
    end
  end


  # 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses

  enum is_deleted: { #会員ステータス
    有効: false,
    退会: true
  }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_one_attached :item_image

  enum is_active: { #販売ステータス
    販売中: true,
    販売停止中: false
  }

  def with_tax_price #税込の表示
    (price * 1.1).floor
  end


  def get_item_image(width,height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpeg')
      item_image.attach(io: File.open(file_path), filename: 'noimage.jpeg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

enum payment_method: { #支払方法
  credit_card: 0,
  transfer: 1
}

enum status: { #注文ステータス
  waiting_for_payment: 0,
  payment_confirmation: 1,
  production: 2,
  preparing_to_ship: 3,
  shipped: 4
}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true

  enum making_status: { #製作ステータス
  can_not_production: 0,
  waiting_for_production: 1,
  production: 2,
  completion_of_production: 3
}

def subtotal
  item.with_tax_price * amount
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!, except: [:index, :show, :top, :about, :edit, :update, :new, :create]
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Nakano_Cake", root_path, class:"navbar-brand" %>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li>
                <%= link_to "商品一覧",  admin_items_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "会員一覧",  admin_customers_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "注文履歴一覧",  admin_root_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "ジャンル一覧",  admin_genres_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method:"delete", class:"nav-link text-light" %>
              </li>
            <% elsif customer_signed_in? %>
              <li>
                <%= link_to "マイページ", customer_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "商品一覧", items_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "カート", cart_items_path, class:"nav-link text-light" %>
              <li>
                <%= link_to "ログアウト", destroy_customer_session_path, method:"delete", class:"nav-link text-light" %>
              </li>
            <% else %>
              <li>
                <%= link_to "About", about_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "商品一覧", items_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "新規登録", new_customer_registration_path, class:"nav-link text-light" %>
              </li>
              <li>
                <%= link_to "ログイン", new_customer_session_path, class:"nav-link text-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <%= yield %>
  </body>
</html>